# This is a "normal" job.
universe = vanilla

# Files to place stdout and stderr
output = output/process_$(Cluster)_$(Process).out
error = error/process_$(Cluster)_$(Process).err
log = log/process_$(Cluster)_$(Process).log
+IsBuildJob = true
#requirements = (Target.HasGluster == true) && (OpSysAndVer =?= "SL6") && (IsBuildSlot == true)
requirements = (Target.HasGluster == true) && (OpSysAndVer =?= "SL6") && (IsBuildSlot == true)

# Copy environment variables from the submit node
getenv = True
environment = "PATH=/bin:/usr/bin:/usr/local/bin LD_LIBRARY_PATH= PYTHONPATH="

# Indicate if/when files should be transfered
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

# Indicate the executable to be run and any other input files needed
executable = launch.bash
transfer_input_files = launch.bash, htc_script/install_mcnp_mure_data.bash, htc_script/std_setup.bash, htc_script/load.bash, TRU_MOX_SOFT_lite.tar.gz

# Command line arguments for the executable
arguments =

# Don't send emails
notification = never

# Request resources
request_cpus = 12
request_memory = 2GB
request_disk = 4GB

queue
